export const experience = [
  {
    role: 'Full-Stack Engineer',
    at: 'Freelance',
    type: 'Part-time',
    time: '2014 — Present',
    loc: 'Remote',
    desc: [
      'Delivered end-to-end web apps for startups and SMBs—from microsites and MVPs to large web applications using different technology stacks.',
      'Designed application-focused cloud architectures on AWS, GCP, and Firebase—serverless-first with managed services—for scalable, low-ops, cost-efficient delivery.',
      'Built React/Angular apps and back ends (serverless and microservices); integrated third-party APIs, auth, payments, AI, and webhooks.',
      'Established CI/CD pipelines and automated unit and E2E testing (GitHub Actions; Jest/Vitest, Cypress/Playwright) to ship predictably and reduce regressions.',
      'Provided technical consulting—architecture/code reviews, tool selection, performance audits, and developer-workflow improvements.',
    ],
    print: true,
    // Max 113 characters per line
    printDesc: [
      'Delivered end-to-end web apps for startups/SMBs—from microsites/MVPs to large applications.',
      'Designed application-focused cloud on AWS, GCP, and Firebase—serverless-first, low-ops, scalable.',
      'Built React/Angular apps and Node back ends; integrated APIs, auth, payments, AI, and webhook flows.',
      'Established CI/CD pipelines and automated unit/E2E tests (GitHub Actions; Jest/Vitest, Cypress/Playwright).',
      'Provided technical consulting: architecture/code reviews, tooling, performance, and developer workflows.',
    ],
  },
  {
    role: 'Full-Stack Engineer (Node.js/TypeScript)',
    at: 'Mishe',
    type: 'Full-time',
    url: 'https://mishe.co',
    time: '2024 — 2025',
    loc: 'United States (Remote)',
    desc: [
      'Modernized a legacy Firebase project: upgraded Node.js (web and Cloud Functions) to LTS, updated dependencies, removed obsolete code, and improved repo structure and developer experience.',
      'Migrated the internal dashboard to Material UI; built reusable components, standardized UI patterns, and shipped some new features.',
      'Organized Firestore data with a custom collection schema/usage analyzer and a dashboard-driven migrations runner integrated into CI/CD with full logging.',
      'Built Stripe dashboards for charges, refunds, transfers, and payouts with flow-specific rules and reconciliation, improving operational visibility.',
      'Set up CI/CD with GitHub Actions and Cloud Pub/Sub: PR checks, staged deployments, and in-dashboard deployment/migration logs.',
      'Quality and reliability: automated unit and E2E tests on PRs; structured logging and observability; caching and load tests to keep responses fast.',
    ],
    print: true,
    printDesc: [
      'Modernized legacy Firebase project: upgraded Node.js to LTS; refactoring; cleaned deps and improved repo/DX.',
      'Migrated the internal dashboard to Material UI; built reusable components and standardized UI patterns.',
      'Organized Firestore data with a schema analyzer and dashboard-driven migrations runner integrated into CI/CD.',
      'Built Stripe operations dashboards (charges, refunds, transfers, payouts) with reconciliation and audit logs.',
      'Set up CI/CD with GitHub Actions + Cloud Pub/Sub: PR checks, staged deploys, and in-dashboard deployment logs.',
      'Quality & reliability: unit/E2E tests on PRs; structured logging/observability; caching and load tests for speed.',
    ],
  },
  {
    role: 'Full-Stack Engineer (Node.js/TypeScript)',
    at: 'JOKR',
    type: 'Full-time',
    url: 'https://www.jokr.com',
    time: '2021 — 2024',
    loc: 'United States (Remote)',
    desc: [
      'Owned NestJS/GraphQL microservices within an Apollo Federation supergraph for the grocery app; shipped features end to end (schema, resolvers, data layer, releases, monitoring).',
      'Built internal React/MUI dashboards and reusable component libraries, streamlining data operations and speeding delivery.',
      'Built an AI-powered product recommendations service using signals such as order history, category affinity, and declared interests; integrated into GraphQL API and internal dashboards.',
      'Improved performance via DataLoader caching and batching, pagination, optimized media delivery, and targeted load testing; sustained thousands of requests/min with low latency.',
      'Set up CI/CD with GitHub Actions and Terraform: PR preview environments and Docker/Kubernetes/Helm deployments across staging and production.',
      'Quality and reliability: 90%+ automated test coverage (Jest/Cypress); Datadog observability and runbooks reduced MTTR; Auth0/JWT hardened access controls.',
    ],
    print: true,
    printDesc: [
      'Owned NestJS/GraphQL services in Apollo Federation; delivered end-to-end features, releases, and monitoring.',
      'Built internal React/MUI dashboards and component libraries; streamlined operations and accelerated delivery.',
      'Built an AI-powered recommendations service from user signals; integrated into the GraphQL API and dashboards.',
      'Boosted performance via caching/batching (DataLoader), pagination, and load tests; sustained high load times.',
      'Set up CI/CD pipelines with GitHub Actions + Terraform: PR previews and Docker/Kubernetes/Helm deployments.',
      'Quality & reliability: 90%+ test coverage; Datadog + runbooks reduced MTTR; Auth0/JWT hardened access controls.',
    ],
  },
  {
    role: 'Full-Stack Engineer (PHP/WordPress)',
    at: 'Point Hacks',
    type: 'Part-time',
    url: 'https://pointhacks.com.au',
    time: '2016 — 2018',
    loc: 'Australia (Remote)',
    desc: [
      'Developed and maintained the main website and its REST API.',
      'Implemented headless WordPress with the WP REST API.',
      'Added Redis server-assisted client-side caching to improve performance.',
      'Configured NGINX load balancing to handle up to 30,000 concurrent requests.',
      'Shipped new user-facing features and improved existing ones.',
    ],
    print: true,
    legacy: true,
  },
  {
    role: 'Full-Stack Engineer (PHP/Symfony)',
    at: 'Dimentians',
    type: 'Full-time',
    url: 'https://dimentians.com',
    time: '2014 — 2016',
    loc: 'Canada (Remote)',
    desc: [
      'Maintained ongoing projects and launched new ones within an Agile team.',
      'Built multiple web apps using PHP and the Symfony framework.',
      'Developed internal apps and microservices on PHP back ends.',
      'Created custom WordPress plugins/themes and resolved configuration/upgrade issues.',
      'Translated wireframes and UX flows into functional, accessible interfaces.',
    ],
    print: true,
    legacy: true,
  },
  {
    role: 'Back-End Engineer (PHP/WordPress)',
    at: 'Axis Digital Solutions',
    type: 'Full-time',
    url: 'https://axsisnet.com/?lang=en',
    time: '2012 — 2014',
    loc: 'Egypt',
    desc: [
      'Led project development with a small cross-functional team (intern + designer).',
      'Built and maintained client websites (both CMS-driven and custom).',
      'Developed a web service for ingesting and storing social-network data.',
      'Implemented and maintained LAMP environments across multiple hosts.',
    ],
    print: false,
    legacy: true,
  },
  {
    role: 'Back-End Engineer (PHP/MySQL)',
    at: 'Queen Tech Solutions',
    url: 'https://queentechsolutions.net',
    time: '2010 — 2012',
    loc: 'Egypt',
    desc: [
      'Built dynamic websites and apps using PHP/MySQL.',
      'Implemented CMS solutions with Joomla and WordPress.',
      'Accelerated delivery with MVC frameworks (CodeIgniter, CakePHP).',
      'Wrote maintainable, standards-compliant code following best practices.',
    ],
    print: false,
    legacy: true,
  },
]

export const education = [
  {
    title: 'Misr University for Science and Technology',
    subtitle: "Bachelor's degree, Physical Therapy",
    time: '2010 – 2016',
  },
  {
    title: 'CS50x — HarvardX / edX',
    subtitle: 'Online education programme of Harvard University',
    url: 'https://www.edx.org/course/introduction-computer-science-harvardx-cs50x',
    time: '2016 – 2017',
    desc: 'C · Python · SQL · Algorithms · Data Structures',
  },
  {
    title: 'Other relevant course work',
    subtitle: 'Various online education programmes',
    time: '2015 – Present',
    desc: 'GraphQL Essentials (2020) · Advanced React (2018) · Advanced JavaScript (2018) · Eloquent JavaScript (2024)',
  },
]
