export const skillTags = {
  back: 'Backend',
  front: 'Frontend',
  devops: 'DevOps',
  soft: 'Software',
  lang: 'Languages',
  frame: 'Frameworks',
  lib: 'Libraries',
  cms: 'Content Management',
  db: 'Databases',
  api: 'APIs',
  test: 'Testing',
  ui: 'User Interface',
  tool: 'Tools',
  build: 'Build Tools',
  deploy: 'Deployment',
  ci: 'CI/CD',
  pkgm: 'Package Managers',
  git: 'Git Hosting',
  dev: 'Development',
  comm: 'Communication',
  env: 'Environment',
}
