name: Feature

on: pull_request

jobs:
  Build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-install-v4-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-install-v4-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true
      - run: pnpm run build
        env:
          BUILD_ENV: staging
      - uses: actions/upload-artifact@v2
        with:
          name: build-art
          path: public
  Deploy:
    if: github.event.pull_request.user.login == 'mohatt'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-art
          path: public
      - run: mv "./public/firebase.json" "./firebase.json"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOHATT }}
          projectId: mohatt
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
