name: Maintenance

on:
  workflow_dispatch:

jobs:
  Deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOHATT }}
          entryPoint: ./maintenance
          projectId: mohatt
          channelId: live
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
