name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy?'
        default: '0'
        required: true

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: ${{ runner.os }}-build-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-build-
      - run: |
          npm -g install pnpm@5.16
          pnpm set verify-store-integrity false
      - run: pnpm install
      - run: pnpm run build -- --prefix-paths
      - if: github.event_name == 'push' || github.event.inputs.deploy == '1'
        uses: actions/upload-artifact@v2
        with:
          name: build-art
          path: public
  deploy:
    if: github.event_name == 'push' || github.event.inputs.deploy == '1'
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-art
          path: public
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: public
