name: Staging

on:
  push:
    branches: [ master ]

jobs:
  Build:
    if: "!contains(github.event.head_commit.message, '[skip ci]')"
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 12
      - uses: actions/cache@v2
        with:
          path: ~/.pnpm-store
          key: pnpm-install-v4-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            pnpm-install-v4-
      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6
          run_install: true
      - run: pnpm run build
        env:
          BUILD_ENV: staging
      - uses: actions/upload-artifact@v2
        with:
          name: build-art
          path: public
  Deploy:
    needs: build
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: build-art
          path: public
      - run: mv "./public/firebase.json" "./firebase.json"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_MOHATT }}'
          projectId: mohatt
          channelId: staging
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels
